name: Close matching PRs

on:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/close-matching-issues@e9e43aad2fa6f06a058cedfd8fb975fd93b56d8f
        with:
          query: 'type:pr label:translation-batch-es'
          token: ${{ secrets.GITHUB_TOKEN }}
